@startuml

[*] --> Idle

Idle --> Pending: MoveAtopAvailableControl / \n EnterControl
Idle -> Ignored: MoveAtopBusyControl

Ignored -> Idle: MoveAtopNothing || \n ControlBecameDisabled
Ignored --> SwitchingToPending: MoveAtopAvailableControl

SwitchingToPending -> Pending: / EnterControl

Pending --> SwitchingToPending: MoveAtopAvailableControl / \n LeaveControl
Pending --> SwitchingToIgnored: MoveAtopBusyControl / \n LeaveControl
Pending --> Idle: MoveAtopNothing || \n ControlBecameDisabled /\n LeaveControl
Pending -left-> Pending: Move / \n NotifyMove
Pending --> Engaged: Down / \n SaveEngaged \n && NotifyDown

Engaged --> Pending: Up / \n NotifyUp
Engaged --> EngagedRemotely: MoveAtopAvailableControl || \n MoveAtopBusyControl || \n MoveAtopNothing / \n NotifyEngagedEscape
Engaged --> Engaged: Move / \n NotifyMove
Engaged --> Idle:  ControlBecameDisabled /\n LeaveControl

EngagedRemotely --> Engaged: MoveAtopEngagedControl / \n NotifyEngagedReturn
EngagedRemotely --> Idle: Up [IsAtopNothing] / \n NotifyUp && \n LeaveControl
EngagedRemotely --> SwitchingToIgnored: Up [IsAtopBusy] / \n NotifyUp && \n LeaveControl
EngagedRemotely --> SwitchingToPending: Up [IsAtopAvailable] / \n NotifyUp && \n LeaveControl
EngagedRemotely --> EngagedRemotely: Move / \n NotifyMove
EngagedRemotely --> Idle:  ControlBecameDisabled /\n LeaveControl

SwitchingToIgnored --> Ignored

@enduml