@startuml

[*] --> Idle

AtopEnabled --> Engaged: Down / \n NotifyDown

AtopEnabled -> Idle: Move [!AtopControl]

Idle -> AtopEnabled: Move [AtopControl]

state AtopEnabled {
    [*] --> Abc
}

state AtopDisabled {
    [*] --> Def
}

Engaged --> Idle: Up [!AtopControl] / \n NotifyLeaveControl
Engaged --> AtopEnabled: Up [AtopControl] / \n NotifyUp

state Engaged {
    [*] -> SubHasEnabled
    
    SubHasEnabled -> ToAtopDisabled: *Any* [!TargetIsEnabled]

    state ToAtopDisabled: exit state

    --

    [*] -> SubEngaged

    SubEngaged --> SubEngaged: Move / NotifyMove
    --
    [*] -> EngagedAtop
    EngagedAtop --> EngagedRemotely: Move [!AtopEngaged] / \n NotifyEngagedEscape

    EngagedRemotely -> EngagedAtop: Move [AtopEngaged] / \n NotifyEngagedReturn

}

@enduml