@startuml
[*] --> Idle

Idle --> Pending: Enter
Pending --> Idle: Leave
Pending -left-> Engaged: Push / RecordAnchor
Engaged --> Pending: Release
Engaged --> EngagedRemotely: Leave
EngagedRemotely --> Engaged: Enter
EngagedRemotely -> Idle: Release


@enduml