@startuml
[*] --> Idle

Idle --> Pending: Enter
Pending --> Idle: Leave
Pending -left-> Engaged: Push / RecordAnchor
Engaged --> Pending: Release
Engaged --> Idle: Leave
Engaged --> EngagedRemotely: EngagedEscape
EngagedRemotely --> Engaged: EngagedReturn
EngagedRemotely -> Idle: Release || Leave


@enduml